### ISSUE TITLE
When absent, "feat" parsed is not 'None'

### ISSUE THREAD

**Issue by mdpoleto** [LBM-EPFL/CLoNe#1]
Hi,

I am testing CLoNe with some of my trajectories and I noticed that, if I leave the flag 'feat' out of the command line, the code parses it as an empty variable and not 'None' as it is suppose to be within the code. Therefore, the code crashes with a warning in line 65:

`Traceback (most recent call last):
  File "/home/******/CLoNe/run_structural.py", line 65, in <module>
    with open(feat, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: ''`

A quick workaround was to define 'feat = "None"' right after the parser, but that quickly becomes unwanted.

Best regards!
--
Marcelo

**Comment by SylvainTraeger** [comment]
Hi,

Thanks for bringing this up ! This only happened when running with all options from command line, it is working fine when using the configuration file. It was a wrongly set default value for the 'feat' flag in the parser (set to "" instead of None).

It is now fixed.

Cheers
